'use client';

import React, { useState } from 'react';
import { Header } from '../../components/Header';
import { Sidebar } from '../../components/Sidebar';
import { HelpCircle, BookOpen, MessageSquare, Phone, FileText } from 'lucide-react';

export default function HelpPage() {
  const [currentTab, setCurrentTab] = useState('help');
  const [searchQuery, setSearchQuery] = useState('');

  return (
    <div className="min-h-screen bg-[#F4F6F9] flex flex-col">
      <Header searchQuery={searchQuery} onSearchChange={setSearchQuery} />

      <div className="flex-1 flex overflow-hidden">
        <Sidebar currentTab={currentTab} onTabChange={setCurrentTab} />

        <main className="flex-1 p-6 overflow-y-auto max-w-[1200px] mx-auto w-full">
          <div className="mb-8 border-b border-slate-200 pb-4">
            <h1 className="text-2xl font-bold text-slate-900">Help & Documentation</h1>
            <p className="text-sm text-slate-500 mt-1">Learn how to use Agni-Netra and get support</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-xs hover:shadow-md transition-shadow cursor-pointer">
              <div className="bg-blue-50 text-blue-600 p-3 rounded-lg w-fit mb-4">
                <BookOpen className="w-6 h-6" />
              </div>
              <h3 className="text-sm font-bold text-slate-900 mb-2">User Guide</h3>
              <p className="text-xs text-slate-500">Comprehensive documentation on platform features and analytics.</p>
            </div>

            <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-xs hover:shadow-md transition-shadow cursor-pointer">
              <div className="bg-emerald-50 text-emerald-600 p-3 rounded-lg w-fit mb-4">
                <FileText className="w-6 h-6" />
              </div>
              <h3 className="text-sm font-bold text-slate-900 mb-2">API Documentation</h3>
              <p className="text-xs text-slate-500">Integrate Agni-Netra data directly into your own tools and systems.</p>
            </div>

            <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-xs hover:shadow-md transition-shadow cursor-pointer">
              <div className="bg-amber-50 text-amber-600 p-3 rounded-lg w-fit mb-4">
                <MessageSquare className="w-6 h-6" />
              </div>
              <h3 className="text-sm font-bold text-slate-900 mb-2">Contact Support</h3>
              <p className="text-xs text-slate-500">Get in touch with our technical team for assistance or bug reports.</p>
            </div>
          </div>

          <div className="bg-white border border-slate-200 rounded-xl shadow-xs overflow-hidden">
            <div className="px-6 py-4 border-b border-slate-100 bg-slate-50/50">
              <h2 className="text-sm font-bold text-slate-800 flex items-center gap-2">
                <HelpCircle className="w-4 h-4 text-blue-600" />
                Frequently Asked Questions
              </h2>
            </div>
            
            <div className="divide-y divide-slate-100">
              <div className="p-6">
                <h4 className="text-sm font-bold text-slate-900 mb-2">How is the Risk Index calculated?</h4>
                <p className="text-xs text-slate-600 leading-relaxed max-w-3xl">
                  The Risk Index (0-100) is a composite score generated by our AI models. It factors in the Fire Radiative Power (FRP), the footprint expansion rate, proximity to critical infrastructure (like refineries or power plants), and prevailing weather conditions (wind speed/direction).
                </p>
              </div>

              <div className="p-6">
                <h4 className="text-sm font-bold text-slate-900 mb-2">What does "Needs Verification" mean?</h4>
                <p className="text-xs text-slate-600 leading-relaxed max-w-3xl">
                  When the system detects a highly anomalous event that deviates significantly from historical baselines, it flags the event for human review. An analyst must review the multispectral evidence and confirm or reject the AI's hypothesis.
                </p>
              </div>

              <div className="p-6">
                <h4 className="text-sm font-bold text-slate-900 mb-2">How frequently is data updated?</h4>
                <p className="text-xs text-slate-600 leading-relaxed max-w-3xl">
                  Agni-Netra ingests data from multiple satellite constellations. Geostationary satellites (like INSAT-3DS) provide updates every 15 minutes, while LEO satellites (like Suomi-NPP VIIRS) provide high-resolution updates roughly every 12 hours depending on the orbital pass.
                </p>
              </div>
            </div>
          </div>
          
        </main>
      </div>
    </div>
  );
}
